service: coin-rates-poll

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::coin-balancer/*"

package:
  include:
    - node_modules
    - services
    - handler.js
    - package.json

functions:
  poll:
    handler: handler.poll
    events:
      - schedule: rate(30 minutes)
      - http:
          path: rates/poll
          method: get
          cors: true
