service: coin-rates-fetch

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::coin-balancer"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::coin-balancer/*"

package:
  include:
    - node_modules
    - services
    - handler.js
    - package.json

functions:
  fetch:
    handler: handler.fetch
    events:
      - http:
          path: rates/fetch
          method: get
          cors: true