service: coin-trades-remove

plugins:
  - serverless-api-compression

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::coin-balancer"
    - Effect: "Allow"
      Action:
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::coin-balancer/*"

package:
  include:
    - node_modules
    - services
    - handler.js
    - package.json

custom:
  stage: ${opt:stage, self:provider.stage}
  contentEncoding:
    contentCompression: 100

functions:
  remove:
    handler: handler.remove
    events:
      - http:
          path: trades/open/remove
          method: post
          cors: true